"use strict";
import { mergeNumbers } from "./strings.js";
//node --experimental-vm-modules node_modules/jest/bin/jest.js

describe("strings operations tests", () => {
  test("merge numbers", () => {
    const input = [
      "e",
      "|",
      "-",
      "1",
      "2",
      "-",
      "1",
      "2",
      "-",
      "1",
      "2",
      "-",
      "1",
      "2",
      "-",
      "1",
      "2",
      "-",
      "1",
      "1",
      "-",
      "-",
      "1",
      "2",
      "-",
      "1",
      "2",
      "-",
      "1",
      "2",
      "-",
      "1",
      "2",
      "-",
      "1",
      "2",
      "-",
      "1",
      "1",
      "-",
      "-",
      "9",
      "-",
      "9",
    ];
    const expectedOutput = [
      "e",
      "|",
      "-",
      "12",
      "-",
      "12",
      "-",
      "12",
      "-",
      "12",
      "-",
      "12",
      "-",
      "11",
      "-",
      "-",
      "12",
      "-",
      "12",
      "-",
      "12",
      "-",
      "12",
      "-",
      "12",
      "-",
      "11",
      "-",
      "-",
      "9",
      "-",
      "9",
    ];
    const indexesToRemove = [4, 7, 10, 13, 16, 19, 23, 26, 29, 32, 35, 38];
    const removedIndexes = mergeNumbers(input);
    expect(input).toStrictEqual(expectedOutput);
    expect(removedIndexes).toBe(indexesToRemove);
  });
});
